services:

  nginx:
    image: nginx:inception
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - wordpress_vol:/wordpress
    restart: on-failure
    depends_on:
      wordpress:
       condition: service_started

  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    secrets:
      - DB_USER_PASSWORD
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb" , "-u", "root", "-e", "SELECT 1"]
      interval: 3s
      timeout: 3s
      retries: 10

  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build: ./requirements/wordpress
    restart: on-failure
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - wordpress_vol:/wordpress
    secrets:
      - WP_PASSWORD
      - WP_SEC_USER_PASS
      - ADMIN_USER_PASS
    depends_on:
      mariadb:
        condition: service_healthy
    
  static_website:
    image: static_website:bonus
    container_name: static_website
    build: ./bonus/static_website/
    ports:
      - 80:80
  
  redis:
    image: redis:bonus
    container_name: redis
    build: ./bonus/redis/
    restart: on-failure
    networks:
      - inception

  ftp_server:
    image: ftp_server:bonus
    container_name: ftp_server
    build: ./bonus/ftp_server/
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress_vol:/wordpress
    env_file:
      - .env
    secrets:
      - FTP_USER_PASS
    ports:
      - 21:21
      - 2100:2100

  ssh_server:
    image: ssh_server:bonus
    container_name: ssh_server
    build: bonus/ssh_server/
    restart: on-failure
    ports:
      - 1111:1111
    volumes:
      - wordpress_vol:/wordpress
    secrets:
      - ROOT_PASS

  adminer:
    image: adminer:bonus
    container_name: adminer
    build: bonus/adminer/
    restart: on-failure
    ports:
      - 9999:9999
    networks:
      - inception

networks:
  inception:

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/makkach/data/mariadb
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/makkach/data/wordpress
      o: bind
    
secrets:
  DB_USER_PASSWORD: 
    file: ../secrets/DB_USER_PASSWORD
  WP_PASSWORD:
    file: ../secrets/WP_PASSWORD
  WP_SEC_USER_PASS:
    file: ../secrets/WP_SEC_USER_PASS
  ADMIN_USER_PASS:
    file: ../secrets/ADMIN_USER_PASS
  FTP_USER_PASS:
    file: ../secrets/FTP_USER_PASS
  ROOT_PASS:
    file: ../secrets/ROOT_PASS
