server
{
    root /wordpress;
    listen 0.0.0.0:443;
    

    location /
    {
        index index.php;
    }

    location ~ \.php$
    {
        fastcgi_pass wordpress:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}