services:
  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    env_file:
      - requirements/wordpress/.env
    volumes:
      - wordpress_vol:/wordpress
    networks:
      - inception
    secrets:
      - WP_PASSWORD
      - WP_ADMIN_PASSWORD
      - WP_USER_PASSWORD
    depends_on:
      mariadb:
        condition: service_healthy


  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    secrets:
      - DB_USER_PASSWORD

    env_file: 
      - requirements/mariadb/.env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-e", "SELECT 1"]
      interval: 3s
      timeout: 3s
      retries: 10
    


  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    env_file:
      - requirements/wordpress/.env
    volumes:
      - wordpress_vol:/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_started


volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/qwerty/data/mariadb
      o: bind

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/qwerty/data/wordpress
      o: bind

networks:
  inception:

secrets:
  DB_USER_PASSWORD:
    file: requirements/mariadb/secrets
  WP_PASSWORD:
    file: requirements/wordpress/WP_PASSWORD
  WP_ADMIN_PASSWORD:
    file: requirements/wordpress/WP_ADMIN_PASSWORD
  WP_USER_PASSWORD:
    file: requirements/wordpress/WP_USER_PASSWORD