services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    env_file:
      - ./.env
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - DB_USER_PASSWORD
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - wordpress_vol:/wordpress
    secrets:
      - WP_PASSWORD

networks:
  inception:

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/makkach/data/mariadb
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/makkach/data/wordpress
      o: bind
    
secrets:
  DB_USER_PASSWORD: 
    file: ../secrets/DB_USER_PASSWORD
  WP_PASSWORD:
    file: ../secrets/WP_PASSWORD
