
events
{
	
}

http
{
	include /etc/nginx/mime.types;
	server {
		listen 443 ssl;
		ssl_certificate /etc/nginx/ssl/cert.pem;
		ssl_certificate_key /etc/nginx/ssl/key.pem;
		root /wordpress;
		location /
		{
			index index.php;
			try_files $uri $uri/ /index.php?$args;
		}
		location ~ \.php$ {
			fastcgi_pass wordpress:9000;
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
